FROM node:20.9.0-alpine3.17

WORKDIR /app

COPY package*.json ./

RUN npm i

COPY .env ./.env
COPY tsconfig.json ./
COPY ./src ./src
COPY ./__tests__ ./__tests__ 
COPY jest.config.ts ./jest.config.ts
COPY jest.setup.ts ./jest.setup.ts

CMD npm run test