name: Compile and push client and server to staging

on:
  push:
    branches: ['staging']
  workflow_dispatch:

jobs:
  build-and-push-server-staging:
    uses: jorisgrls/tgc-avril23/.github/workflows/build-backend.yml@staging
    secrets:
      DOCKERHUB_USERNAME: jorisgls
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      image_name: jorisgls/tgc-avril23-staging-back

  build-and-push-client-staging:
    uses: jorisgrls/tgc-avril23/.github/workflows/build-frontend.yml@staging
    secrets:
      DOCKERHUB_USERNAME: jorisgls
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      image_name: jorisgls/tgc-avril23-staging-front
      fileupload_api_url: https://files.staging.joris.tech
      graphql_api_url: https://api.staging.joris.tech

  notify:
    needs:
      - build-and-push-server-staging
      - build-and-push-client-staging
    runs-on: ubuntu-latest
    steps:
      - name: Call VPS webhook to update staging
        uses: wei/curl@v1
        with:
          args: https://ops.joris.tech/hooks/update-staging
